"""update_schema_for_registry

Revision ID: cdb135f1f886
Revises: None
Create Date: 2026-08-22 00:26:39.823693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdb135f1f886'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'product_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product_images', 'image_path',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('product_images', 'image_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('product_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('product_images', 'thumbnail_path',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               nullable=True)
    op.alter_column('product_images', 'width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_images', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_images', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_images', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               nullable=True)
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('products', 'barcode',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_constraint('products_barcode_key', 'products', type_='unique')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_unique_constraint('products_barcode_key', 'products', ['barcode'])
    op.alter_column('products', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'weight',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('products', 'barcode',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'description')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.alter_column('product_images', 'file_hash',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('product_images', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_images', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_images', 'width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_images', 'thumbnail_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('product_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('product_images', 'image_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('product_images', 'image_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('product_images', 'product_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
